apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example-backend
    spec:
      containers:
      - name: server
        image: localhost:5000/kubelearn:1.1
        imagePullPolicy: IfNotPresent
        command: ["python"]
        args: ["-m", "example.server"]
        ports:
          - containerPort: 5001
            name: server-port
            protocol: TCP
        env:
          - name: CELERY_BROKER_URL
            valueFrom:
              configMapKeyRef:
                name: example-config
                key: celery_broker
          - name: CELERY_RESULT_BACKEND
            valueFrom:
              configMapKeyRef:
                name: example-config
                key: celery_backend
          #  value: "redis://redis-service:6379/0"
          #  value: "redis://redis-service:6379/0"
      - name: celery-worker
        image: localhost:5000/kubelearn:1.1
        imagePullPolicy: IfNotPresent
        command: [ "celery" ]
        args: ["-A", "example.worker", "worker", "--loglevel=DEBUG" ]
        env:
          - name: CELERY_BROKER_URL
            value: "redis://redis-service:6379/0"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis-service:6379/0"
      - name: celery-flower
        image: localhost:5000/kubelearn
        imagePullPolicy: IfNotPresent
        command: ["celery"]
        args: ["flower", "--port=5555"]
        ports:
          - containerPort: 5555
            name: flower-port
            protocol: TCP
        env:
          - name: CELERY_BROKER_URL
            value: "redis://redis-service:6379/0"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis-service:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-backend-service
  name: example-backend-service
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: server-port
      protocol: TCP
      name: server
    - port: 5555
      targetPort: flower-port
      protocol: TCP
      name: celery-flower
  selector:
    app: example-backend
