---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-backend
  name: example-backend
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: server
      protocol: TCP
      name: server
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: redis-stack
    - port: 5555
      targetPort: 5555
      protocol: TCP
      name: celery-flower
  selector:
    app: example-backend