apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example-server
    spec:
      containers:
      - name: server
        image: localhost:5000/kubelearn
        imagePullPolicy: Always
        command: ["python"]
        args: ["-m", "example.server"]
        ports:
          - containerPort: 5001
            name: server-port
            protocol: TCP
        env:
          - name: CELERY_BROKER_URL
            value: "redis://redis:6379"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-service
  name: example-service
spec:
  type: ClusterIP
  selector:
    app: example-server
  ports:
    - name: task-service
      protocol: TCP
      port: 8080
      targetPort: server-port
